### ISSUE TITLE
8.2.3.0 - concurrent issue might occur

### ISSUE THREAD

**Issue by AndreyFilchenkov** [SitecoreSupport/Sitecore.Support.96029#1]
The following concurrent issue with the initial version of the patch might occur.
```
ERROR Cannot start analytics Tracker
Exception: System.IndexOutOfRangeException
Message: Index was outside the bounds of the array.
Source: mscorlib
   at System.Collections.Generic.List`1.Add(T item)
   at Sitecore.Support.Analytics.Pipelines.ParseReferrer.AddNotProvidedKeywords.GetHostNamesList()
   at Sitecore.Support.Analytics.Pipelines.ParseReferrer.AddNotProvidedKeywords.Process(ParseReferrerArgs args)
   at (Object , Object[] )
...
```
The issue is fixed in the 8.2.3.1 version of the patch.

**Comment by AndreyFilchenkov** [comment]
Closed via 5debcce77c662bd4a12e748bb49a0873efcc7d50 commit
